name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: true
    - name: Build
      run: dotnet build ./src
    - name: Test
      run: dotnet test ./src/OuraRingDataIngest.Tests
